In [1]:
from steer_core.DataManager import DataManager
from steer_materials.CellMaterials.Electrode import Binder
from steer_materials import __version__
from datetime import datetime as dt
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['binder_materials',
 'conductive_additive_materials',
 'current_collector_materials',
 'insulation_materials',
 'separator_materials',
 'cells',
 'cathode_materials',
 'anode_materials']

In [4]:
db.drop_table('binder_materials')

In [5]:
db.create_table(table_name='binder_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT'
})

In [6]:
# materials 

pvdf = Binder(name='PVDF', density=1.78, specific_cost=12, color='#e5e5e5')
sbr = Binder(name='SBR', density=0.94, specific_cost=1, color='#f4e3d7')
cmc = Binder(name='CMC', density=1.6, specific_cost=3, color='#d6cfc7')
paa = Binder(name='PAA', density=1.22, specific_cost=3, color='#e4dada')
alg = Binder(name='Alginate', density=1.6, specific_cost=2, color='#c2b280')

materials = [pvdf, sbr, cmc, paa, alg]

pickled_materials = [m.serialize() for m in materials]

In [7]:
# store data for current collectors

db.insert_data(table_name='binder_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
}))

In [8]:
db.get_binder_materials(most_recent=False)

,name,object,date,version
0,PVDF,gASVCQEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
1,SBR,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
2,CMC,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
3,PAA,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
4,Alginate,gASVDQEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9

In [9]:
db.get_binder_materials()

,name,object,date,version
0,PVDF,gASVCQEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
1,SBR,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
2,CMC,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
3,PAA,gASVCAEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9
4,Alginate,gASVDQEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-16 14:38:56,0.1.9