In [1]:
from steer_core.DataManager import DataManager
from steer_materials.CellMaterials.Electrode import ConductiveAdditive
from steer_opencell_design import __version__
from datetime import datetime as dt
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['cells',
 'conductive_additive_materials',
 'current_collector_materials',
 'insulation_materials',
 'separator_materials',
 'anode_materials',
 'binder_materials',
 'cathode_materials']

In [4]:
db.drop_table('conductive_additive_materials')

In [5]:
db.create_table(table_name='conductive_additive_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT'
})

In [6]:
# materials 

superp = ConductiveAdditive(name='Super P', density=2.0, specific_cost=15.0, color='#111111')
ketjenblack = ConductiveAdditive(name='Ketjenblack EC-600JD', density=1.8, specific_cost=30.0, color='#0f0f0f')
acetylene_black = ConductiveAdditive(name='Acetylene Black', density=1.8, specific_cost=15.0, color='#1a1a1a')
graphite = ConductiveAdditive(name='Graphite', density=2.2, specific_cost=10.0, color='#4d4d4d')
carbon_nanotubes = ConductiveAdditive(name='Carbon Nanotubes', density=1.75, specific_cost=250.0, color='#1b1b1b')
graphene = ConductiveAdditive(name='Graphene', density=2.2, specific_cost=350.0, color='#2c2c2c')
vgcf = ConductiveAdditive(name='Vapor Grown Carbon Fibers', density=2.0, specific_cost=75, color='#262626')

materials = [superp, ketjenblack, acetylene_black, graphite, carbon_nanotubes, graphene, vgcf]

pickled_materials = [m.serialize() for m in materials]

In [7]:
# store data for current collectors

db.insert_data(table_name='conductive_additive_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
}))

In [8]:
db.get_conductive_additive_materials(most_recent=False)

,name,object,date,version
0,Super P,gASVJgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
1,Ketjenblack EC-600JD,gASVMwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
2,Acetylene Black,gASVLgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
3,Graphite,gASVJwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
4,Carbon Nanotubes,gASVLwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
5,Graphene,gASVJwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
6,Vapor Grown Carbon Fibers,gASVKgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5

In [9]:
db.get_conductive_additive_materials()

,name,object,date,version
0,Super P,gASVJgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
1,Ketjenblack EC-600JD,gASVMwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
2,Acetylene Black,gASVLgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
3,Graphite,gASVJwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
4,Carbon Nanotubes,gASVLwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
5,Graphene,gASVJwEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5
6,Vapor Grown Carbon Fibers,gASVKgEAAAAAAACMJ3N0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-08-12 14:14:39,0.3.5