In [1]:
from steer_core.DataManager import DataManager
from steer_materials.CellMaterials.Base import InsulationMaterial
from steer_materials import __version__
from datetime import datetime as dt
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['cells',
 'insulation_materials',
 'separator_materials',
 'anode_materials',
 'binder_materials',
 'cathode_materials',
 'conductive_additive_materials',
 'current_collector_materials']

In [4]:
db.drop_table('insulation_materials')

In [5]:
db.create_table(table_name='insulation_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT'
})

In [6]:
# materials 

aluminium_oxide_95 = InsulationMaterial(
    name='Aluminium Oxide, 95%', 
    density=3.65, 
    specific_cost=20, 
    color='#B0A99F'
)

aluminium_oxide_96 = InsulationMaterial(
    name='Aluminium Oxide, 96%', 
    density=3.72, 
    specific_cost=55, 
    color='#D4CDC5'
)

aluminium_oxide_99 = InsulationMaterial(
    name='Aluminium Oxide, 99.5%', 
    density=3.87, 
    specific_cost=115, 
    color='#EAEAEA'
)

aluminium_oxide_999 = InsulationMaterial(
    name='Aluminium Oxide, 99.9%', 
    density=3.92, 
    specific_cost=225, 
    color='#F7F7F7'
)

sapphire = InsulationMaterial(
    name='Sapphire', 
    density=3.99, 
    specific_cost=1000, 
    color='#A9C8E3'
)

In [7]:
materials = [
    aluminium_oxide_95, 
    aluminium_oxide_96, 
    aluminium_oxide_99, 
    aluminium_oxide_999, 
    sapphire
]

pickled_materials = [m.serialize() for m in materials]

In [8]:
# store data for current collectors

db.insert_data(table_name='insulation_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
}))

In [9]:
db.get_insulation_materials(most_recent=False)

,name,object,date,version
0,"Aluminium Oxide, 95%",gASVIAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
1,"Aluminium Oxide, 96%",gASVIAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
2,"Aluminium Oxide, 99.5%",gASVIgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
3,"Aluminium Oxide, 99.9%",gASVIwEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
4,Sapphire,gASVFgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11

In [10]:
db.get_insulation_materials()

,name,object,date,version
0,"Aluminium Oxide, 95%",gASVIAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
1,"Aluminium Oxide, 96%",gASVIAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
2,"Aluminium Oxide, 99.5%",gASVIgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
3,"Aluminium Oxide, 99.9%",gASVIwEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11
4,Sapphire,gASVFgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-09-30 09:12:05,0.1.11